server:
  port: 8081

spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop

ribbon:
  IsSecure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
---

spring:
  profiles: default    
  datasource:
    url: jdbc:mysql://localhost/fortunes
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
