insert into fortunes (id, text) values (1000, 'If you continually give, you will continually have. ');
insert into fortunes (id, text) values (1001, 'The one you love is closer than you think. ');
insert into fortunes (id, text) values (1002, 'The time is right to make new friends. ');
insert into fortunes (id, text) values (1003, 'A thrilling time is in your immediate future. ');
insert into fortunes (id, text) values (1004, 'Something you lost will soon turn up. ');
insert into fortunes (id, text) values (1005, 'Your many hidden talents will become obvious to those around you. ');
insert into fortunes (id, text) values (1006, 'A member of your family will soon do something that will make you proud.Happy news is on its way to you. ');
insert into fortunes (id, text) values (1007, 'You will have a very pleasant experience. ');
insert into fortunes (id, text) values (1008, 'You will live a long, happy life. ');
insert into fortunes (id, text) values (1009, 'You will take a chance in something in the near future. ');
insert into fortunes (id, text) values (1010, 'You are talented in many ways. ');
insert into fortunes (id, text) values (1011, 'People are naturally attracted to you.');
insert into fortunes (id, text) values (1012, 'You learn from your mistakes... You will learn a lot today.');
insert into fortunes (id, text) values (1013, 'If you have something good in your life, don't let it go!');
insert into fortunes (id, text) values (1014, 'Your shoes will make you happy today.');
insert into fortunes (id, text) values (1015, 'The man or woman you desire feels the same about you.');
insert into fortunes (id, text) values (1016, 'A dream you have will come true.');
insert into fortunes (id, text) values (1017, 'Never give up. You're not a failure if you don't give up.');
insert into fortunes (id, text) values (1018, 'You will become great if you believe in yourself.');
insert into fortunes (id, text) values (1019, 'A very attractive person has a message for you.');
insert into fortunes (id, text) values (1020, 'You can make your own happiness.');
insert into fortunes (id, text) values (1021, 'The greatest risk is not taking one.');
insert into fortunes (id, text) values (1022, 'Serious trouble will bypass you.');
insert into fortunes (id, text) values (1023, 'A short stranger will soon enter your life with blessings to share.');
insert into fortunes (id, text) values (1024, 'Now is the time to try something new.');
insert into fortunes (id, text) values (1025, 'If winter comes, can spring be far behind?');
insert into fortunes (id, text) values (1026, 'Keep your eye out for someone special.');
insert into fortunes (id, text) values (1027, 'Everyone agrees. You are the best.');